version: '3'

services:

  book-api:
    build:
      context: ./book-api
    environment:
       - DATABASE_URL=book-database:27017
    ports:
      - 5001:5000
    depends_on:
      - book-database
    
  front-end:
    build:
      context: ./front-end
    environment:
      - BOOK_API_SERVER=http://book-api:5000
    ports:
      - 5000:5000
    depends_on:
      - book-api
    
  book-database:
    image: mongo:latest
    ports:
       - 27017:27017
    